# -*- mode: org; coding: utf-8-unix; fill-column: 80 -*-

* What

Stefil is a Common Lisp testing (anti-)framework where tests are
merely augmented ~DEFUN*~'s, coupled with a smarter ~ASSERT~ macro
(called ~IS~). Unexpected situations are integrated into the condition
system with additional restarts.

* Status

It's a mature project that has been exercised a lot.

It doesn't mean though that there's no room left for improvements, but
development has stalled for years.

Stefil was the pioneer of this kind of testing (anti-)frameworks, but
I think there are better alternatives today. See below.

* Where

The project's [[https://github.com/hu-dwim/hu.dwim.stefil][Github page]] is the primary communication channel.

* Why

The interactive CL development workflow with Slime is excellent, and I
saw no reason for all the preexisting testing frameworks to interfere
with it.

* Alternatives
** Try
After a cursory look /[[https://github.com/melisgl/try][Try]]/ seems to be a more thorough
implementation of the same idea.

Hat tip to Gábor Melis!
** Fiasco
[[https://github.com/capitaomorte/fiasco][Fiasco]] is a friendly fork.

Here's the pre-fork discussion: https://github.com/luismbo/stefil/issues/9

> in short: at this time i (attila) am not working actively on
> hu.dwim.stefil, and IIRC the proposed changes were too divergent, so
> we agreed to fork off fiasco from hu.dwim.stefil.
